In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.20.1


In [15]:
aa=np.arange(5)

In [16]:
aa

array([0, 1, 2, 3, 4])

In [17]:
bb=[1,1,1]
cc=[1,1,1]
dd=[1,1,1]

In [18]:
ab=np.array([bb,cc,dd])

In [19]:
ab

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
np.full((3,3),True,dtype=bool,order=None)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [26]:
arr=np.arange(10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [31]:
arr[arr%2==0]

array([0, 2, 4, 6, 8])

In [32]:
arr[arr%2==1]=-1

In [33]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [34]:
aa=np.arange(10)

In [35]:
aa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
ab=aa[0:5]
bb=aa[5:10]

In [37]:
ac=np.array([ab,bb])

In [268]:
ac

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [269]:
type(ac)

numpy.ndarray

In [41]:
aa.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,-1)

In [60]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [62]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [65]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [66]:
a=np.array([1,2,3])

In [78]:
aa=[np.repeat(a,3)]

In [79]:
bb=[np.tile(a,3)]

In [80]:
np.hstack([aa,bb])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [87]:
a = np.array([1,2,3,2,3,4,3,4,5,6,12])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [88]:
np.intersect1d(a,b)

array([2, 4])

In [89]:
np.common_type(a,b)

numpy.float64

In [97]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [98]:
c=np.intersect1d(a,b)

In [99]:
af=a[a!=c]

In [100]:
af

array([1, 2, 3, 4])

In [101]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [102]:
np.setdiff1d(b,a)

array([6, 7, 8, 9])

In [103]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [105]:
a.shape

(10,)

In [107]:
b.shape

(10,)

In [110]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [111]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [119]:
ab=a[(a>=5)&(a<=10)]

In [120]:
ab

array([ 6,  9, 10])

In [127]:
index=np.where((a>=5)&(a<=10))
index

(array([1, 3, 4], dtype=int64),)

In [126]:
a[index]

array([ 6,  9, 10])

In [146]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y


In [147]:
pair_max=np.vectorize(maxx,otypes=[int])

In [148]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [149]:
x=pair_max(a,b)

In [157]:
x

array([6, 7, 9, 8, 9, 7, 5])

In [158]:
def ll(m,n):
    if m==n:
        print("a")
    else :
        print("b")

In [190]:
common=np.vectorize(ll,otypes=[float])

In [178]:
y=common(x,a)

b
a
a
a
b
b
a


type(y)

In [187]:
y.shape

(7,)

In [188]:
y.reshape(1,7)

array([[nan, nan, nan, nan, nan, nan, nan]])

##

In [197]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [204]:
# np.swapaxes(arr,3,1)

In [210]:
arr[:,[1,0,2]]#swap

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [211]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [212]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [217]:
arr[::-1,:]#reverse

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [218]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [225]:
np.random.randn(15).reshape(5,3)

array([[-0.68666045, -0.5048048 ,  0.25563217],
       [ 0.41060649, -0.65638936,  0.48135132],
       [-0.16411331, -0.38108543,  1.60310502],
       [-0.5567967 ,  0.08462316,  0.49071032],
       [-0.15855077, -0.3582899 ,  0.67338176]])

In [230]:
np.random.randint(low=5,high=10,size=(5,3))+np.random.random((5,3))

array([[8.35815395, 7.56635922, 9.29637656],
       [9.3306411 , 9.77337776, 9.55486635],
       [6.44636158, 5.08864793, 9.27736516],
       [9.57116077, 9.2848771 , 6.85124474],
       [5.80516633, 5.7969795 , 7.32575569]])

In [231]:
np.random.uniform(5,10,size=(5,3))

array([[6.77287958, 6.69521227, 6.19268007],
       [7.25205781, 9.31232433, 9.54734039],
       [5.98947713, 8.59638168, 7.61538349],
       [6.08450844, 9.17426345, 8.2279167 ],
       [7.76323178, 6.55051172, 5.2082317 ]])

In [236]:
a = np.arange(15)

In [237]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [256]:
np.set_printoptions(threshold=15)

In [257]:
np.arange(17)

array([ 0,  1,  2, ..., 14, 15, 16])

In [260]:
np.set_printoptions(threshold=100000000000)

In [261]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [262]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [265]:
import pandas as pd

In [267]:
type(url)

str